---
layout: Resume
title: Tam Tran's Resume
---  
minhtamtran.work@gmail.com | 208-671-3212 | https://www.linkedin.com/in/tam-tran-b37a9123b/ |    
https://github.com/Tam-Tran-24002    

Tam Tran is an aspiring Data Scientist currently pursuing a Bachelor of Science in Data Science with a minor in Business Analytics and a Cloud Computing certificate. With a growing interest in data analytics, machine learning, and cloud computing, Tam is passionate about solving real-world problems through data. Eager to learn and gain hands-on experience, Tam has proficiency in Python, SQL, R, Excel, Tableau, and machine learning models. Focused on enhancing skills in data visualization, data analytics, predictive modeling, and database management, Tam is actively seeking opportunities to apply and further develop expertise in a dynamic business environment.   

# Education
Bachelor of Science in Data Science    
Minor in Business Analytics & Cloud Computing Certificate      
Brigham Young University - Idaho | Expected Graduation: December 2027   

# Key Skills
• Data Analysis: Python (Pandas, NumPy, Matplotlib, LetsPlot, Seaborn, Scikit-learn), SQL, R      
• Machine Learning: Data preprocessing (train-test split, feature engineering, encoding categorical data), Classification Models (Decision Trees,Random Forest, KNN, XGBoost), Regression Models      
• Business Intelligence Tools: Tableau      
• Microsoft Office Suite: Word, Excel, PowerPoint, Outlook  

# Professional Experience
## Tutor | Data Science Lab & Tutoring Center
Rexburg, Idaho | January 2025 - Present    
Brigham Young University - Idaho                                                                 
• Tutor 200+ students in Data Intuition and Insights (Tableau), Data Science Programming (Python, SQL, Machine Learning), and Programming with Functions    
• Break down complex data science concepts for both technical and non-technical students, using clear explanations and practical examples, leading to increased comprehension and engagement     

## Teaching Assistant
Rexburg, Idaho | September 2024 - Present    
Brigham Young University - Idaho                                                               
• Provide academic support to 250+ students in Introduction to Database, Intro to Programming, and Data Science Programming courses through tutoring, grading, and constructive feedback    
• Collaborate with professors to refine course materials, enhancing student engagement and improving learning outcomes    
• Facilitate lab sessions and office hours to reinforce key concepts and assist with coding assignments     

## New Student Mentor
Rexburg, Idaho | September 2024 - December 2024    
Brigham Young University - Idaho                                                                 
• Guided weekly gatherings for 40+ new students, providing support for academic and personal challenges      
• Boosted student engagement by 30% through 150+ one-on-one and group consultancy meetings      
• Managed attendance for 40+ students and coordinate 5+ resources to enhance learning outcomes and student success      
• Strengthened course organization and lesson planning to ensure students achieve academic success        

## Product Manager
Ho Chi Minh, Vietnam | February 2023 - February 2024      
AIESEC in Vietnam                                                                       
• Led a team of 8 members, delivering top-tier customer service for Global Volunteer projects and generating over $1550 in revenue    
• Analyzed 500+ lead and customer data points to generate actionable insights, improve customer experience, and optimize business strategy    
• Collaborated with cross-functional teams across 10+ countries to enhance the customer journey and drive seamless service delivery    
• Achieved an 87.5% retention rate of members through weekly performance data analysis and the implementation of data-driven strategies    
• Awarded Function Excellence with a 90% goal achievement rate      

# Volunteer Experience
## Marketing Team Leader | BAC - International Business Club
Ho Chi Minh, Vietnam | December 2021 - December 2022    
Ton Duc Thang University                                                              
• Directed and improved a 6-member team by analyzing performance metrics and implementing weekly workflow adjustments, resulting in a 20% increase in operational efficiency and streamlined processes      
• Trained 5 team members on advanced Excel techniques, resulting in a 30% reduction in operational processing time and significantly boosting overall team performance       

# Relevant Projects
## Machine Learning – Bootcamp                                                     
January 2024 - Present            
• Deployed Random Forest, Decision Trees, K-Nearest Neighbors (KNN), and XGBoost on real-world datasets, achieving 90% accuracy      
• Optimized model performance through feature engineering, train-test split, and categorical encoding      
• Extracted actionable insights to support data-driven decisions and enhance model interpretability         


<!-- ### Footer

Last updated: May 2013 -->